version: "3"
services:
  mysql:
    image: mysql:5.7
    platform: linuxx86_64 # NOTE: M1 Macだとこれ設定しないとちゃんと動かない
    container_name: mysql
    environment:
      MYSQL_DATABASE: my_testdb
      MYSQL_USER: test_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - default # いらないかも

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 9090:80

  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    container_name: app
    environment:
      MYSQL_SERVER: mysql
      TZ: Asia/Tokyo
      DEBUG: app:*
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app:cached
    working_dir: /app
    command: yarn dev
    networks:
      - default
    depends_on:
      - mysql

networks:
  default:
# コンテナが削除されてもデータが消えずに保持される
volumes:
  mysqldata:
